<?php

namespace Database\Seeders;

use App\Models\Article;
use Illuminate\Database\Seeder;

class ArticlesSeeder extends Seeder
{
    public function run(): void
    {
        $articles = [
            // Hardware - Portáteis
            [
                'referencia' => 'HW-PORT-001',
                'nome' => 'Portátil Dell Latitude 5430',
                'tipo' => 'produto',
                'gama' => 'premium',
                'descricao' => 'Portátil empresarial 14", Intel i7-1265U, 16GB RAM, 512GB SSD, Windows 11 Pro',
                'preco' => 1299.00,
                'iva_percentagem' => 23,
                'preco_com_iva' => 1597.77,
                'stock_quantidade' => 15,
                'estado' => 'ativo',
            ],
            [
                'referencia' => 'HW-PORT-002',
                'nome' => 'Portátil Lenovo ThinkPad T14 Gen 3',
                'tipo' => 'produto',
                'gama' => 'premium',
                'descricao' => 'Portátil 14", AMD Ryzen 7 PRO, 32GB RAM, 1TB SSD, Windows 11 Pro',
                'preco' => 1499.00,
                'iva_percentagem' => 23,
                'preco_com_iva' => 1843.77,
                'stock_quantidade' => 10,
                'estado' => 'ativo',
            ],
            [
                'referencia' => 'HW-PORT-003',
                'nome' => 'Portátil HP ProBook 450 G9',
                'tipo' => 'produto',
                'gama' => 'normal',
                'descricao' => 'Portátil 15.6", Intel i5-1235U, 8GB RAM, 256GB SSD, Windows 11 Pro',
                'preco' => 799.00,
                'iva_percentagem' => 23,
                'preco_com_iva' => 982.77,
                'stock_quantidade' => 20,
                'estado' => 'ativo',
            ],

            // Hardware - Monitores
            [
                'referencia' => 'HW-MON-001',
                'nome' => 'Monitor LG UltraWide 34WN80C-B',
                'tipo' => 'produto',
                'gama' => 'premium',
                'descricao' => 'Monitor curvo 34", QHD 3440x1440, USB-C 60W, HDR10, IPS',
                'preco' => 549.00,
                'iva_percentagem' => 23,
                'preco_com_iva' => 675.27,
                'stock_quantidade' => 8,
                'estado' => 'ativo',
            ],
            [
                'referencia' => 'HW-MON-002',
                'nome' => 'Monitor Dell P2422H',
                'tipo' => 'produto',
                'gama' => 'normal',
                'descricao' => 'Monitor 24", Full HD 1920x1080, IPS, ajustável em altura, HDMI/DP',
                'preco' => 189.00,
                'iva_percentagem' => 23,
                'preco_com_iva' => 232.47,
                'stock_quantidade' => 30,
                'estado' => 'ativo',
            ],
            [
                'referencia' => 'HW-MON-003',
                'nome' => 'Monitor ASUS ProArt PA279CV',
                'tipo' => 'produto',
                'gama' => 'premium',
                'descricao' => 'Monitor 27", 4K UHD, IPS, 100% sRGB, calibrado de fábrica, USB-C',
                'preco' => 449.00,
                'iva_percentagem' => 23,
                'preco_com_iva' => 552.27,
                'stock_quantidade' => 5,
                'estado' => 'ativo',
            ],

            // Hardware - Periféricos
            [
                'referencia' => 'HW-PER-001',
                'nome' => 'Teclado Logitech MX Keys',
                'tipo' => 'produto',
                'gama' => 'premium',
                'descricao' => 'Teclado wireless retroiluminado, multi-device, layout PT, bateria recarregável',
                'preco' => 89.00,
                'iva_percentagem' => 23,
                'preco_com_iva' => 109.47,
                'stock_quantidade' => 25,
                'estado' => 'ativo',
            ],
            [
                'referencia' => 'HW-PER-002',
                'nome' => 'Rato Logitech MX Master 3S',
                'tipo' => 'produto',
                'gama' => 'premium',
                'descricao' => 'Rato wireless ergonómico, 8000 DPI, scroll MagSpeed, multi-device',
                'preco' => 99.00,
                'iva_percentagem' => 23,
                'preco_com_iva' => 121.77,
                'stock_quantidade' => 20,
                'estado' => 'ativo',
            ],
            [
                'referencia' => 'HW-PER-003',
                'nome' => 'Webcam Logitech Brio 4K',
                'tipo' => 'produto',
                'gama' => 'premium',
                'descricao' => 'Webcam 4K Ultra HD, autofocus, HDR, campo de visão ajustável, microfone integrado',
                'preco' => 179.00,
                'iva_percentagem' => 23,
                'preco_com_iva' => 220.17,
                'stock_quantidade' => 12,
                'estado' => 'ativo',
            ],
            [
                'referencia' => 'HW-PER-004',
                'nome' => 'Headset Jabra Evolve2 65',
                'tipo' => 'produto',
                'gama' => 'premium',
                'descricao' => 'Headset wireless, cancelamento de ruído, certificado MS Teams, autonomia 37h',
                'preco' => 189.00,
                'iva_percentagem' => 23,
                'preco_com_iva' => 232.47,
                'stock_quantidade' => 15,
                'estado' => 'ativo',
            ],

            // Hardware - Networking
            [
                'referencia' => 'HW-NET-001',
                'nome' => 'Switch Cisco CBS350-24T-4G',
                'tipo' => 'produto',
                'gama' => 'premium',
                'descricao' => 'Switch gerido 24 portas Gigabit + 4 portas SFP, Layer 3 Lite, PoE+',
                'preco' => 899.00,
                'iva_percentagem' => 23,
                'preco_com_iva' => 1105.77,
                'stock_quantidade' => 5,
                'estado' => 'ativo',
            ],
            [
                'referencia' => 'HW-NET-002',
                'nome' => 'Access Point UniFi U6 Pro',
                'tipo' => 'produto',
                'gama' => 'premium',
                'descricao' => 'AP Wi-Fi 6, dual-band, 5.3 Gbps, PoE, gestão UniFi Network',
                'preco' => 149.00,
                'iva_percentagem' => 23,
                'preco_com_iva' => 183.27,
                'stock_quantidade' => 20,
                'estado' => 'ativo',
            ],
            [
                'referencia' => 'HW-NET-003',
                'nome' => 'Firewall pfSense SG-2100',
                'tipo' => 'produto',
                'gama' => 'premium',
                'descricao' => 'Firewall/router, 4 portas Gigabit, processador ARM Cortex A53 Dual-Core',
                'preco' => 399.00,
                'iva_percentagem' => 23,
                'preco_com_iva' => 490.77,
                'stock_quantidade' => 8,
                'estado' => 'ativo',
            ],

            // Hardware - Storage/Backup
            [
                'referencia' => 'HW-STO-001',
                'nome' => 'NAS Synology DS923+',
                'tipo' => 'produto',
                'gama' => 'premium',
                'descricao' => 'NAS 4 baías, AMD Ryzen R1600, 4GB RAM, 2x 10GbE, suporta até 18 unidades',
                'preco' => 649.00,
                'iva_percentagem' => 23,
                'preco_com_iva' => 798.27,
                'stock_quantidade' => 4,
                'estado' => 'ativo',
            ],
            [
                'referencia' => 'HW-STO-002',
                'nome' => 'Disco WD Red Plus 4TB NAS',
                'tipo' => 'produto',
                'gama' => 'normal',
                'descricao' => 'Disco rígido 3.5", 4TB, 5400 RPM, SATA 6Gb/s, CMR, otimizado para NAS',
                'preco' => 99.00,
                'iva_percentagem' => 23,
                'preco_com_iva' => 121.77,
                'stock_quantidade' => 40,
                'estado' => 'ativo',
            ],
            [
                'referencia' => 'HW-STO-003',
                'nome' => 'UPS APC Smart-UPS SMT1500I',
                'tipo' => 'produto',
                'gama' => 'premium',
                'descricao' => 'UPS 1500VA/1000W, LCD, gestão via rede, hot-swap baterias',
                'preco' => 699.00,
                'iva_percentagem' => 23,
                'preco_com_iva' => 859.77,
                'stock_quantidade' => 6,
                'estado' => 'ativo',
            ],

            // Software/Licenças
            [
                'referencia' => 'SW-LIC-001',
                'nome' => 'Microsoft 365 Business Standard',
                'tipo' => 'servico',
                'gama' => 'normal',
                'descricao' => 'Licença anual por utilizador, Office apps + Teams + OneDrive 1TB',
                'preco' => 10.50,
                'iva_percentagem' => 23,
                'preco_com_iva' => 12.92,
                'stock_quantidade' => 999,
                'estado' => 'ativo',
            ],
            [
                'referencia' => 'SW-LIC-002',
                'nome' => 'Windows 11 Pro OEM',
                'tipo' => 'produto',
                'gama' => 'normal',
                'descricao' => 'Licença OEM Windows 11 Professional 64-bit PT',
                'preco' => 159.00,
                'iva_percentagem' => 23,
                'preco_com_iva' => 195.57,
                'stock_quantidade' => 50,
                'estado' => 'ativo',
            ],
            [
                'referencia' => 'SW-LIC-003',
                'nome' => 'Acronis Cyber Protect Standard',
                'tipo' => 'servico',
                'gama' => 'premium',
                'descricao' => 'Licença anual backup e antimalware, 1 workstation, 250GB cloud storage',
                'preco' => 79.00,
                'iva_percentagem' => 23,
                'preco_com_iva' => 97.17,
                'stock_quantidade' => 999,
                'estado' => 'ativo',
            ],

            // Serviços
            [
                'referencia' => 'SRV-001',
                'nome' => 'Instalação e Configuração de Workstation',
                'tipo' => 'servico',
                'gama' => 'normal',
                'descricao' => 'Instalação de SO, drivers, software base, configuração rede e domínio',
                'preco' => 75.00,
                'iva_percentagem' => 23,
                'preco_com_iva' => 92.25,
                'stock_quantidade' => 999,
                'estado' => 'ativo',
            ],
            [
                'referencia' => 'SRV-002',
                'nome' => 'Manutenção Mensal IT (até 10 utilizadores)',
                'tipo' => 'servico',
                'gama' => 'normal',
                'descricao' => 'Suporte remoto 8x5, atualizações, monitorização, backup, 4h presencial/mês',
                'preco' => 450.00,
                'iva_percentagem' => 23,
                'preco_com_iva' => 553.50,
                'stock_quantidade' => 999,
                'estado' => 'ativo',
            ],
            [
                'referencia' => 'SRV-003',
                'nome' => 'Configuração Servidor Windows',
                'tipo' => 'servico',
                'gama' => 'premium',
                'descricao' => 'Instalação e configuração Windows Server, Active Directory, DNS, DHCP, File Server',
                'preco' => 890.00,
                'iva_percentagem' => 23,
                'preco_com_iva' => 1094.70,
                'stock_quantidade' => 999,
                'estado' => 'ativo',
            ],
            [
                'referencia' => 'SRV-004',
                'nome' => 'Migração para Microsoft 365',
                'tipo' => 'servico',
                'gama' => 'premium',
                'descricao' => 'Análise, planeamento, migração email/dados, configuração Teams, formação (até 25 users)',
                'preco' => 2500.00,
                'iva_percentagem' => 23,
                'preco_com_iva' => 3075.00,
                'stock_quantidade' => 999,
                'estado' => 'ativo',
            ],
            [
                'referencia' => 'SRV-005',
                'nome' => 'Auditoria de Segurança IT',
                'tipo' => 'servico',
                'gama' => 'premium',
                'descricao' => 'Análise infraestrutura, testes penetração, relatório vulnerabilidades, recomendações',
                'preco' => 1800.00,
                'iva_percentagem' => 23,
                'preco_com_iva' => 2214.00,
                'stock_quantidade' => 999,
                'estado' => 'ativo',
            ],
            [
                'referencia' => 'SRV-006',
                'nome' => 'Consultoria IT (hora)',
                'tipo' => 'servico',
                'gama' => 'normal',
                'descricao' => 'Consultoria técnica IT, análise sistemas, planeamento, troubleshooting',
                'preco' => 65.00,
                'iva_percentagem' => 23,
                'preco_com_iva' => 79.95,
                'stock_quantidade' => 999,
                'estado' => 'ativo',
            ],
            [
                'referencia' => 'SRV-007',
                'nome' => 'Intervenção Presencial (hora)',
                'tipo' => 'servico',
                'gama' => 'normal',
                'descricao' => 'Suporte técnico presencial, resolução problemas, instalação hardware/software',
                'preco' => 55.00,
                'iva_percentagem' => 23,
                'preco_com_iva' => 67.65,
                'stock_quantidade' => 999,
                'estado' => 'ativo',
            ],
        ];

        foreach ($articles as $article) {
            Article::create($article);
        }

        $this->command->info('✅ Criados ' . count($articles) . ' artigos de informática!');
    }
}
